[system]

[geometry]
type = "HexagonalLattice"
a = 2.46

[kpoints]
grid = [60, 60]

[model]
type = "Graphene"
t = 2.8
EF = 0.0

[interaction]
type = "BareCoulomb"
cutoff = 0.01

[field]
type = "DirectChannel"

[task]
type = "scan_spectral_function"
qpath_points = [[0.0, 0.0], [1.703, 0.0], [1.703, 0.983], [0.0, 0.0]]
qpath_labels = ["Γ", "M", "K", "Γ"]
npoints_each_line = 50
omega_range = [0.0, 5.0]
omega_points = 400
T_val = 0.01
eta = 0.02

[plot]
enable = true
