[system]
n_workers = 4

[geometry]
type = "SquareLattice"
a = 1.5
kgrid_grid = [50, 50]

[model]
type = "TightBinding"
EF = 0.0
t = 1.0

[interaction]
type = "Constant"
V0 = -2.5

[field]
type = "BCSReducedPairing"
symmetry = "p_wave"

[task]
type = "compute_phase_transition_data"
phi_range = [0.0, 1.0]
phi_points = 100
T_range = [0.1, 0.5]
T_points = 10
